- name: Clone repo
  become: yes
  become_user: "{{user}}"
  git: update=yes version=HEAD repo=ssh://git@github.com/{{repo}}.git dest=/home/{{user}}/{{service}}

- name: npm install
  shell: HOME=/home/{{user}} NODE_ENV=production npm install
  args:
    chdir: /home/{{user}}/{{service}}
  become: yes
  become_user: "{{user}}"
  notify:
    - Restart {{service}}

- name: Copy config
  become: yes
  become_user: "{{user}}"
  template: src=.tarsrc dest=/home/{{user}}/{{service}}/.tarsrc
  notify:
    - Restart {{service}}

- name: Copy Upstart config
  become: yes
  template: src=upstart/upstart.conf dest=/etc/init/{{service}}.conf mode=0644 force=yes

- name: Ensure the app is running
  become: yes
  service: name={{service}} state=started enabled=yes

- name: Copy Nginx config
  become: yes
  copy: src=nginx/ dest=/etc/nginx/conf.d/ mode=0644 force=yes
  notify:
    - Restart Nginx
